window.blackcrown_manifest = [
    { dir: "address", title: "The Dunnage Label" },
    { dir: "bestiary", title: "A Peripheral Bestiary" },
    { dir: "bindlestiff", title: "The Bindlestiff" },
    { dir: "bindlestiff2", title: "The Bindlestiff [alternate]" },
    { dir: "cambium", title: "The Cambium" },
    { dir: "cambium2", title: "The Cambium [alternate]" },
    { dir: "diplomat", title: "The Diplomat" },
    { dir: "fretgay", title: "The Fretgay" },
    { dir: "fretgay2", title: "The Fretgay [alternate]" },
    { dir: "frontispiece", title: "The Bowspirit" },
    { dir: "gates", title: "No Ingress K29" },
    { dir: "guttering", title: "Some Guttering" },
    { dir: "hislatitude", title: "His Latitude, The Stars" },
    { dir: "incineration", title: "Incineration Order [Incinerated Misc. K97]" },
    { dir: "jenny", title: "Jenny Garganta" },
    { dir: "macrophile", title: "The Macrophile" },
    { dir: "pervertslimbs", title: "Up Amongst A Pervert's Limbs" },
    { dir: "pilot", title: "Jenny Garganta [pilot]" },
    { dir: "pilot2", title: "The Pilot's Book K894" },
    { dir: "player", title: "A Record Of Breath" },
    { dir: "player2", title: "A Record Of Breath [alternate]" },
    { dir: "player3", title: "New Breath 1" },
    { dir: "player4", title: "New Breath 2" },
    { dir: "potential", title: "Loss Of Potential D57" },
    { dir: "river", title: "The River Upstairs" },
    { dir: "riverupstairs", title: "The River Upstairs [alternate]" },
    { dir: "rosetto", title: "Dear Rosetto" },
    { dir: "semestress", title: "The Semestress" },
    { dir: "stars", title: "His Latitude, The Stars [alternate]" },
    { dir: "tightwalk", title: "The Tight Walk P8923" },
    { dir: "vaseandcup", title: "The Vase and Cup K20" },
    { dir: "vignettes", title: "Vignettes On A Disaster, Apparently Not In My Honour" },
    { dir: "waylemap", title: "The Wayle Map" },
    { dir: "waylemap2", title: "The Wayle Map [alternate]" },
    { dir: "weevil", title: "The Pageant Weevil" },
    { dir: "weevilhunt1", title: "The Abbieannia Problem" },
    { dir: "weevilhunt2", title: "The Roasting Dance" },
    { dir: "weevilhunt3", title: "The Weevil Hunt" },
    { dir: "worstcook", title: "The Worst Cook [Transcript M12]" },
    { dir: "yourgreatwork", title: "Your Great Work" }
];
